services:
  localstack:
    image: localstack/localstack:stable
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,lambda
      - DEBUG=0
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "./functions:/etc/functions"
      - "/var/run/docker.sock:/var/run/docker.sock"