name: Deploy touch function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-touch.yaml'

jobs:
  deploy:
    name: Deploy function
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: sudo apt-get update && sudo apt-get install -y zip
      - run: zip -j function.zip *.mjs
        working-directory: ./functions/touch
      - run: |
          aws lambda update-function-code \
            --function-name cucumber-reports-touch-prod \
            --zip-file fileb://$(pwd)/functions/touch/function.zip
